variable "region" {
  default = "us-east-1"
  description = "The AWS region."
}

variable "env" {
  description = "Environment: unstable, demo, ..."
}

variable "domain" {
  default = "sciety.org"
  description = "The domain."
}

variable "google_site_verification_record" {
  default = "google-site-verification=CkWhogOskZm7nRTmjdHiD8q2NbfXOns-vp5qeHEK_5w" // Value generated by Paul Shannon
  description = "TXT entry generated at https://search.google.com/search-console"
}

variable "map_users" {
  default = [
    {
      userarn  = "arn:aws:iam::540790251273:user/GiorgioSironi"
      username = "GiorgioSironi"
      groups   = ["system:masters"]
    },
    {
      userarn  = "arn:aws:iam::540790251273:user/DanielHaarhoff"
      username = "DanielHaarhoff"
      groups   = ["system:masters"]
    },
    {
      userarn  = "arn:aws:iam::540790251273:user/ChrisWilkinson"
      username = "ChrisWilkinson"
      groups   = ["system:masters"]
    },
    {
      userarn  = "arn:aws:iam::540790251273:user/DavidMoulton"
      username = "DavidMoulton"
      groups   = ["system:masters"]
    },
    {
      userarn  = "arn:aws:iam::540790251273:user/WillByrne"
      username = "WillByrne"
      groups   = ["system:masters"]
    },
    {
      userarn  = "arn:aws:iam::540790251273:user/GithubActions"
      username = "GithubActions"
      groups   = ["system:masters"]
    },
  ]
  description = "IAM users that can access the cluster"
}

variable "slack_webhook_path" {
  description = "e.g. /services/T025.../.../... from https://elifesciences.slack.com/services/B01HJK68E4Q" 
}
