name: Franklin

on:
  push:
    branches:
      - master

env:
  TERRAFORM: ../../terraform

jobs:

  terraform:

    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          scripts/download-terraform.sh

      - name: Plan
        run: |
          cd tf/envs/franklin
          $TERRAFORM init --backend-config="key=franklin/terraform.tfstate" -input=false
          $TERRAFORM plan -out /tmp/franklin.plan \
            -var "slack_webhook_path=${{ secrets.SLACK_WEBHOOK_PATH }}"
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}

      - name: Apply
        run: |
          cd tf/envs/franklin
          $TERRAFORM apply /tmp/franklin.plan
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_CREDENTIALS }}
          
      - name: Kubernetes smoke tests
        run: |
          aws eks update-kubeconfig --name libero-eks--franklin 
          helm ls
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: us-east-1
