name: Franklin

on:
  push:
    branches:
      - master

env:
  TERRAFORM: ../../terraform

jobs:

  apply:

    runs-on: ubuntu-18.04

    steps:
      - uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          scripts/download-terraform.sh

      - name: Plan
      - run: |
          cd tf/envs/franklin
          rm -rf .terraform && $TERRAFORM init --backend-config="key=franklin/terraform.tfstate" -input=false
          $TERRAFORM plan -out /tmp/franklin.plan
          
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}